apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a5mxg9kxp-python
  janus-idp.io/tekton: a5mxg9kxp-python
  backstage.io/kubernetes-id: a5mxg9kxp-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: a5mxg9kxp-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
